class InvalidTransition(ValueError): pass
TRANSITIONS={
 'MANIFEST_INTERNAL_INTEGRITY_PENDING':{'RUNNING_INTERNAL_TESTS'},
 'RUNNING_INTERNAL_TESTS':{'MANIFEST_INTERNAL_INTEGRITY_PASS','BLOCKED_INTERNAL_MANIFEST_INTEGRITY'},
 'BLOCKED_INTERNAL_MANIFEST_INTEGRITY':{'MANIFEST_INTERNAL_INTEGRITY_PENDING'},
 'MANIFEST_INTERNAL_INTEGRITY_PASS':{'READY_FOR_PROVIDER_PREFLIGHT'},
 'READY_FOR_PROVIDER_PREFLIGHT':{'PROVIDER_PREFLIGHT_PASS'},
 'PROVIDER_PREFLIGHT_PASS':{'MODEL_MANIFEST_FROZEN'},
 'MODEL_MANIFEST_FROZEN':{'BENCH20_SCREEN_READY'},
}
def transition(state,to):
    if to not in TRANSITIONS.get(state,set()): raise InvalidTransition(f'{state} -> {to}')
    return to
